// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekkofnbezezlazxqtftg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVra29mbmJlemV6bGF6eHF0ZnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODk5NzgsImV4cCI6MjA2MTU2NTk3OH0.sbgu9CrWbkBh6SHoQdbDmgtZ17v8a61p72YJRzTziRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);